services:
  frontend:
    build:
      context: frontend
      target: dev
      #args:
        #- VITE_BACKEND_URL=${VITE_BACKEND_URL}
    ports:
      - 80:80
    #depends_on:
    #    - backend
  #backend:
  #  build:
  #    context: backend
