version: '3.9'

networks:
    reviewiiith_network:
        ipam:
            config:
                - subnet: ${HOST_SUBNET}

services:
    reviewiiith:
        build:
            context: .
            dockerfile: Dockerfile
            args:
                HOST_SUBPATH: ${HOST_SUBPATH}
                MSG_MAX_LEN: ${MSG_MAX_LEN}
        networks:
            reviewiiith_network:
                ipv4_address: ${HOST_PRIVATE}
        env_file:
            - ./.env
        tty: true

